# ex:
#   packageExtensions:
#     webpack@*:
#       dependencies:
#         lodash: ^4.15.0
#       peerDependencies:
#         webpack-cli: "*"
#       peerDependenciesMeta:
#         webpack-cli:
#           optional: true
---
packageExtensions:
  storybook@*:
    peerDependencies:
      webpack: "*"
  "@chromatic-com/storybook@*":
    peerDependencies:
      react: "*"
  "@storybook/core@*":
    peerDependencies:
      storybook: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      "@types/react": "*"
